version: "3"
services: 
  drupal:
    image : drupal
    ports:
      - "8080:80"
    volumes:
      - drupalvolmodules:/var/www/html/modules
      - drupalvolprofiles:/var/www/html/profiles
      - drupalvolthemes:/var/www/html/themes
      - drupalvolsites:/var/www/html/sites
  database:
    image : postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgvol:/var/lib/postgresql/data

volumes:
  pgvol:
  drupalvolmodules:
  drupalvolprofiles:
  drupalvolthemes:
  drupalvolsites:




  