version: "3"
services:
  frontend:
    image : nginx
    ports:
      - "80:80"
    networks:
      - mynet
    depends_on:
      - backend
    volumes:
      - /c/Users/Administrator/Desktop/Sumit/Docs/DockerImages/compose/html:/usr/share/nginx/html
  backend:
    image : node
    networks:
      - mynet
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - younet
networks:
  mynet:
  younet:
volumes:
  nginxvol1: