FROM ubuntu

RUN apt-get update && \
    apt-get install nginx -y && \
    apt-get install htop && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

WORKDIR /var/www/html

COPY index.html index.html

VOLUME ["/var/www/html"]


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]