version: "3"
services:
  frontend:
    image : nginx
    ports:
      - "8080:80"
    networks:
      - mynet
  database:
    image : postgres
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - mynet
  otherservice:
    image: nginx
    ports:
      - "5004:80"
    networks:
      - younet

networks:
  mynet:
  younet: